/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author aakg2
 */
public class amountpage extends javax.swing.JFrame {

    /**
     * Creates new form amountpage
     */
    public amountpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        bal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        acc1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mob = new javax.swing.JTextField();
        amo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        jLabel5.setText("TRANSACTION");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 49));

        bal.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        bal.setForeground(new java.awt.Color(255, 0, 51));
        bal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balActionPerformed(evt);
            }
        });
        getContentPane().add(bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 79, 160, 69));

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("BALANCE");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 74, 117, 69));

        acc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc1ActionPerformed(evt);
            }
        });
        getContentPane().add(acc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 87, 206, 52));

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Account Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 82, 199, 52));
        getContentPane().add(cname, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 231, 206, 42));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 228, 199, 42));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Mobile");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 293, 91, 42));
        getContentPane().add(mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 293, 206, 42));

        amo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amoActionPerformed(evt);
            }
        });
        getContentPane().add(amo, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 230, 160, 45));

        jLabel6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 204));
        jLabel6.setText("Amount");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 228, 117, 40));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton1.setText("Deposit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 313, -1, -1));

        jButton2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton2.setText("Withdraw");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(627, 313, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jButton3.setText("Show");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 255));
        jButton4.setText("Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 358, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\aakg2\\Downloads\\transaction.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void balActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balActionPerformed

    private void acc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acc1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           Connection c=null;
        PreparedStatement p=null;
        ResultSet s=null;

        try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            c=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\aakg2\\OneDrive\\Documents\\bank_sys_user.accdb");
            String sql="select amount from customerinformation where account_no='"+acc1.getText()+"'";
            p=c.prepareStatement(sql);
            s=p.executeQuery();
            int a=0;
           if(s.next()){
               a=s.getInt("amount");
               a+=Integer.parseInt(amo.getText());
           }
         String sql2="update customerinformation set amount='"+a+" 'where account_no='"+acc1.getText()+"'";
           p=c.prepareStatement(sql2);
            p.execute();
            String sql3="select amount from customerinformation where account_no='"+acc1.getText()+"'";
             p=c.prepareStatement(sql);
            s=p.executeQuery();
            if(s.next()){
                bal.setText(s.getString("amount"));
            }
        }                                    
             catch (Exception e){
              JOptionPane.showMessageDialog(null, e);
    }          // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void amoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
           Connection c=null;
        PreparedStatement p=null;
        ResultSet s=null;

        try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            c=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\aakg2\\OneDrive\\Documents\\bank_sys_user.accdb");
            String sql="select fname+' '+lname as name, amount,mobile from customerinformation where account_no='"+acc1.getText()+"'";
            p=c.prepareStatement(sql);
            s=p.executeQuery();
            if(s.next()){
                bal.setText(s.getString("amount"));
                cname.setText(s.getString("name"));
                mob.setText(s.getString("mobile"));
            }
           }  catch (Exception e){
              JOptionPane.showMessageDialog(null, e);
    }//GEN-LAST:event_jButton3ActionPerformed
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection c=null;
        PreparedStatement ps=null;
        ResultSet rs=null;
        
        try{
        Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
        c=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\aakg2\\OneDrive\\Documents\\bank_sys_user.accdb");
        String sql="select amount from customerinformation where account_no='"+acc1.getText()+"'";
        ps=c.prepareStatement(sql);
        rs=ps.executeQuery();
        
         int a=0;
        if(rs.next()&& rs.getInt("amount")>=Integer.parseInt(amo.getText())){
            //if( rs.getInt("amount")>=Integer.parseInt(amo.getText())){
             a=rs.getInt("amount");
              a-=Integer.parseInt(amo.getText());
             String sql1="update customerinformation set amount='"+a+"'where account_no='"+acc1.getText()+"'";
              ps=c.prepareStatement(sql1);
             ps.execute();
         }
            
         //}
        else{
                JOptionPane.showMessageDialog(null, "Withdraw not possible");
            }
     
        String sql2="select amount from customerinformation where account_no='"+acc1.getText()+"'";
        ps=c.prepareStatement(sql2);
        rs=ps.executeQuery();
        if(rs.next()){
            bal.setText(rs.getString("amount"));
        }
        }
        catch (Exception e){
        JOptionPane.showMessageDialog(null,e);
    
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Bankdetails o=new Bankdetails();
        o.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(amountpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(amountpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(amountpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(amountpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new amountpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acc1;
    private javax.swing.JTextField amo;
    private javax.swing.JTextField bal;
    private javax.swing.JTextField cname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField mob;
    // End of variables declaration//GEN-END:variables
}
