/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bank.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author aakg2
 */
public class Transfer extends javax.swing.JFrame {

    /**
     * Creates new form Transfer
     */
    public Transfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        bal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        acc1 = new javax.swing.JTextField();
        acc2 = new javax.swing.JTextField();
        amnt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        bal1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Transfer To");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 180, 103, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("Account Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 67, -1, -1));

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(262, 130, 81, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 255, 204));
        jLabel3.setText("Balance");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 67, 67, -1));
        getContentPane().add(bal, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 61, 121, 42));

        jButton2.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton2.setText("Transfer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("Amount");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 180, 67, -1));

        acc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc1ActionPerformed(evt);
            }
        });
        getContentPane().add(acc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 64, 121, 37));

        acc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc2ActionPerformed(evt);
            }
        });
        getContentPane().add(acc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 178, 121, 35));

        amnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amntActionPerformed(evt);
            }
        });
        getContentPane().add(amnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(418, 175, 121, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText("Bank Transfer");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 251, 28));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setText("Balance");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 226, 100, 40));
        getContentPane().add(bal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 226, 121, 40));

        jButton3.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\aakg2\\Downloads\\transfer.jpg")); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                   Connection c=null;
        PreparedStatement p=null;
        ResultSet s=null;

        try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            c=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\aakg2\\OneDrive\\Documents\\bank_sys_user.accdb");
            String sql="select fname+' '+lname as name, amount,mobile from customerinformation where account_no='"+acc1.getText()+"'";
            p=c.prepareStatement(sql);
            s=p.executeQuery();
            if(s.next()){
                bal.setText(s.getString("amount"));
              
              
            }
            else{
                JOptionPane.showMessageDialog(null,"Account Do not exist");
            }
           }  catch (Exception e){
              JOptionPane.showMessageDialog(null, e);
    }                                        
    
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void amntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amntActionPerformed

    private void acc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acc1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                   Connection c=null;
        PreparedStatement ps=null;
        ResultSet rs=null;
        ResultSet rs1=null;

        try{
            Class.forName("net.ucanaccess.jdbc.UcanaccessDriver");
            c=DriverManager.getConnection("jdbc:ucanaccess://C:\\Users\\aakg2\\OneDrive\\Documents\\bank_sys_user.accdb");
            String sql="select amount from customerinformation where account_no='"+acc1.getText()+"'";
            ps=c.prepareStatement(sql);
            rs=ps.executeQuery();
            
            String sql4="select amount from customerinformation where account_no='"+acc2.getText()+"'";
            ps=c.prepareStatement(sql4);
            rs1=ps.executeQuery();
              int a=0;
                int b=0;
            if(rs.next()&& rs1.next() && rs.getInt("amount")>=Integer.parseInt(amnt.getText())){
              
              //  if(rs.getInt("amount")>=Integer.parseInt(amnt.getText())){
                    a=rs.getInt("amount");
                    a-=Integer.parseInt(amnt.getText());
                    
                    String sql1="update customerinformation set amount='"+a+"'where account_no='"+acc1.getText()+"'";
                    ps=c.prepareStatement(sql1);
                    ps.execute();
                    
           
         
           
             b=rs1.getInt("amount");
              b+=Integer.parseInt(amnt.getText());
               String sql2="update customerinformation set amount='"+b+"'where account_no='"+acc2.getText()+"'";
                ps=c.prepareStatement(sql2);
                 ps.execute();
            
            
                    //}
          //  else{
              //      JOptionPane.showMessageDialog(null, "Transfer Not possible");
              //  }
               
          
            
            }
             else{
                    JOptionPane.showMessageDialog(null, "Transfer Not possible");
                }
                  String sql3="select amount from customerinformation where account_no='"+acc2.getText()+"'";
                ps=c.prepareStatement(sql3);
                rs=ps.executeQuery();
                if(rs.next()){
                    bal1.setText(rs.getString("amount"));
                }
                    
                String sql5="select amount from customerinformation where account_no='"+acc1.getText()+"'";
                ps=c.prepareStatement(sql5);
                rs=ps.executeQuery();
                if(rs.next()){
                    bal.setText(rs.getString("amount"));   
                }
                
                
        }    
             catch (Exception e){
              JOptionPane.showMessageDialog(null, e);
    }                                        
    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void acc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acc2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Bankdetails o=new Bankdetails();
        o.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField acc1;
    private javax.swing.JTextField acc2;
    private javax.swing.JTextField amnt;
    private javax.swing.JTextField bal;
    private javax.swing.JTextField bal1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
